export const ELEMENT_DOMINANCE_TEXT: Record<string, string> = {
  Feu: "Dominante Feu : une énergie qui a besoin d'agir, d'initier, de s'enthousiasmer. Le risque, si elle n'est pas canalisée, est l'impulsivité ou l'essoufflement rapide. La piste de maturation consiste à apprendre à tenir un élan sur la durée d'un projet entier, pas seulement sur son démarrage, sans pour autant éteindre ce qui en fait la force.",
  Terre: "Dominante Terre : un besoin de concret, de stabilité et de résultats tangibles. Le risque, si elle est trop marquée, est la rigidité ou une difficulté à lâcher prise. La piste de maturation consiste à apprendre qu'on peut accepter un changement sans perdre la solidité déjà construite.",
  Air: "Dominante Air : une énergie tournée vers les idées, l'échange et la mise en relation. Le risque, si elle est trop marquée, est de rester dans la tête, en évitant l'ancrage émotionnel ou concret. La piste de maturation consiste à apprendre à laisser une idée redescendre dans le corps et le ressenti, pas seulement circuler entre les têtes.",
  Eau: "Dominante Eau : une sensibilité émotionnelle et intuitive au premier plan. Le risque, si elle est trop marquée, est de se laisser submerger ou d'avoir du mal à poser des limites claires. La piste de maturation consiste à apprendre à poser une limite sans se sentir coupable, sans pour autant perdre la richesse de cette sensibilité.",
};

export const MODALITY_DOMINANCE_TEXT: Record<string, string> = {
  Cardinal: "Dominante Cardinale : une énergie qui initie, qui aime démarrer les choses. Le risque est de multiplier les débuts sans toujours aller au bout. La piste de maturation consiste à apprendre à choisir un chantier et à le mener à son terme avant d'en ouvrir un autre.",
  Fixe: "Dominante Fixe : une énergie qui tient dans la durée, persévérante et loyale à ses choix. Le risque est une résistance excessive au changement. La piste de maturation consiste à apprendre qu'ajuster une trajectoire en cours de route n'est pas un abandon, c'est aussi une forme de constance.",
  Mutable: "Dominante Mutable : une énergie adaptable, qui s'ajuste facilement au contexte. Le risque est une certaine dispersion ou un manque de colonne vertébrale dans la durée. La piste de maturation consiste à apprendre à garder un fil directeur stable au milieu de tous les ajustements, pour que la souplesse ne se transforme jamais en absence de cap.",
};
