import type { PointKey, ZodiacSign } from "../types";

export const PLANET_IN_SIGN_EN: Partial<Record<PointKey, Record<ZodiacSign, string>>> = {
  sun: {
    belier: "A direct, enterprising temperament, needing to initiate rather than wait around. Aries' natural combativeness gives courage, sometimes at the cost of patience.",
    taureau: "An identity built over time and through consistency: a need for concrete security, a taste for simple pleasure, attachment to what is stable and reliable.",
    gemeaux: "A curious, changeable identity, fed by exchange and novelty. The need to vary interests can give an image that's a bit hard to pin down.",
    cancer: "A sensitive, protective identity, deeply tied to emotional and family life. Inner security comes through attachment and the memory of bonds.",
    lion: "An identity that needs to be seen and recognized, with generosity and a flair for the dramatic. The Sun is \"at home\" here: self-assertion is a central drive.",
    vierge: "An identity built through usefulness, precision, a concern for doing things right. Self-demand is strong, sometimes at the expense of self-confidence.",
    balance: "An identity defined largely through relating to others: a need for balance, fairness, harmony, sometimes at the cost of difficulty deciding alone.",
    scorpion: "An intense identity that does nothing by halves, marked by a need for truth and transformation. Control and emotional intensity are central themes.",
    sagittaire: "An identity that needs open air, horizons and meaning: optimism, frankness, a taste for freedom of movement and thought.",
    capricorne: "An identity built over time, with seriousness and patient ambition. The need for structure and social recognition is marked, often softening with age.",
    verseau: "An identity defined by deliberate difference and independence of mind, with a strong interest in the collective and ideas for the future.",
    poissons: "A fluid, empathetic identity, sometimes hard to pin down because so permeable to its surroundings. A strong need for an ideal or inspiration to connect to.",
  },
  moon: {
    belier: "Quick, direct emotional reactions, a need for security met through action rather than introspection. Impatience can mask real vulnerability.",
    taureau: "A sensitivity that needs stability, sensory and material bearings. Comfort comes through physical ease, routine and a reassuring physical presence.",
    gemeaux: "Emotional needs met through verbal exchange and mental stimulation. The mind sometimes takes over from raw feeling, as a way of managing emotion.",
    cancer: "The Moon is in its own sign here: raw sensitivity, a very developed emotional memory, a strong need for a nest and family security.",
    lion: "An emotional need for recognition and demonstrativeness: one loves and wants to be loved with flair. Pride can make vulnerability hard to show.",
    vierge: "A sensitivity that's reassured by order, usefulness and control of detail. Anxiety settles by \"doing,\" by being useful, by organizing reality.",
    balance: "A strong emotional need for harmony and togetherness: inner security depends heavily on the quality of relationships and the absence of conflict.",
    scorpion: "An intense, deep, sometimes secretive sensitivity: emotions are never lived by halves, with a real need for trust and emotional truth.",
    sagittaire: "An emotional need for freedom and space: inner security comes through movement, discovery, the ability to believe in something bigger.",
    capricorne: "A reserved sensitivity, protected through self-control and restraint. Emotional security is often built late, but then very solidly.",
    verseau: "A more mental than merging relationship to emotions, with a need for freedom even in the closest bonds. Friendship often matters as much as passion.",
    poissons: "A porous, empathetic sensitivity, sometimes to the point of losing itself in others'. A great need for space to withdraw, daydream, or seek spirituality.",
  },
  mercury: {
    belier: "A quick, spontaneous mind that decides fast — sometimes before examining everything. Debate is stimulating; nuance is a skill to cultivate.",
    taureau: "A concrete, steady mind that needs time to mature but, once formed, rarely changes its opinion. Practical common sense rather than abstract theory.",
    gemeaux: "Mercury is in its element here: curiosity in every direction, verbal ease, enjoyment of contact and quick learning, sometimes at the cost of depth.",
    cancer: "A mind colored by emotion and memory: reasoning also happens through feeling, intuition, family experience — not just pure logic.",
    lion: "An expression that needs to convince and leave a mark: a flair for narrative, firm conviction, sometimes a lack of listening to opposing views.",
    vierge: "Mercury is also very much at home here: analytical mind, concern for exact detail, sharp critical sense, a taste for what's useful and verifiable.",
    balance: "A mind that weighs the pros and cons, seeks compromise and diplomatic phrasing — sometimes at the cost of indecision or overly consensual speech.",
    scorpion: "A mind that digs beneath the surface: a sense for psychology, for what's implied, a taste for taboo or complex subjects rather than small talk.",
    sagittaire: "A broad mind that prefers the big picture and big ideas to details. Direct frankness, sometimes tactless, but always sincere.",
    capricorne: "A structured mind that gets to the point with method and seriousness. Thinking is often oriented toward concrete usefulness and the long term.",
    verseau: "An original mind that likes to go off the beaten path and imagine the future differently. Good capacity for abstraction, sometimes at the cost of emotional detachment.",
    poissons: "An intuitive, associative mind, closer to imagery and feeling than to linear logic — valuable for creativity, harder for factual precision.",
  },
  venus: {
    belier: "A spontaneous, direct desire that enjoys the chase as much as the settled relationship. Attraction happens fast, sometimes at the cost of constancy.",
    taureau: "Venus is in its element here: affirmed sensuality, a taste for shared comfort, loyalty and deep attachment to what is stable and sensorially satisfying.",
    gemeaux: "A desire fed by exchange, lightness and variety: seduction happens through words and curiosity, with a need to never be bored.",
    cancer: "A tender, protective affection that seeks merging and security in the bond. Attachment is deep, sometimes possessive out of fear of loss.",
    lion: "A generous, theatrical desire that loves to seduce with flair and be admired in return. The heart is big, and so is the pride.",
    vierge: "A reserved affection, often expressed through acts of service rather than grand displays. The concern for doing things right extends to the relationship.",
    balance: "Venus is also very much at home here: a sharp sense of relational harmony, charm, a marked aesthetic sense, a strong need for balanced partnership.",
    scorpion: "An intense, exclusive desire that isn't satisfied with superficiality. Attachment is deep, sometimes jealous or all-consuming, but rarely lukewarm.",
    sagittaire: "An affection that needs air and freedom: one loves sharing ideas and adventures, with a certain reluctance toward routine confinement.",
    capricorne: "A serious desire that commits gradually but durably. Seduction sometimes takes a back seat to the concrete building of the bond.",
    verseau: "An original affection that favors friendship and freedom within the relationship. Routine and possessiveness are poorly tolerated; independence is non-negotiable.",
    poissons: "A romantic, merging desire, sometimes idealized to the point of illusion. Great capacity for romantic empathy, with a risk of self-sacrifice in the bond.",
  },
  mars: {
    belier: "Mars is in its element here: direct energy, courage, a need to act fast and take on challenges. Impatience and impulsiveness are the flip side of this vitality.",
    taureau: "An energy that engages slowly but with formidable endurance. Anger, rare, takes a long time to rise — and just as long to settle.",
    gemeaux: "An energy expressed through words and mental agility rather than physical force. A need to vary fronts of action, at the risk of scattering.",
    cancer: "An indirect combativeness, more defensive than offensive: one fights mainly to protect loved ones or emotional territory. Anger sometimes shows as sulking.",
    lion: "A proud energy that loves to assert itself with flair and be seen succeeding. The courage is real, and so is the ego.",
    vierge: "An energy applied to detail and concrete efficiency: one acts with method rather than brute force, and self-criticism can hold back momentum.",
    balance: "A combativeness that prefers strategy and diplomacy to direct confrontation — at the risk of stalling too long before acting.",
    scorpion: "Mars is traditionally very much at home here: intense determination, capacity for resistance and counter-attack, marked sexual and instinctual energy.",
    sagittaire: "An enthusiastic energy that commits to causes or ideals with a sometimes-abrupt frankness. Needs plenty of room to unfold.",
    capricorne: "An energy that plays the long game and aims at concrete long-term goals, with discipline. Patient ambition rather than impulsiveness.",
    verseau: "A combativeness readily expressed for collective causes, with a rebellious streak toward authority and convention.",
    poissons: "A less frontal energy, working through intuition, avoidance of direct conflict, or commitment to idealistic causes rather than personal ones.",
  },
  jupiter: {
    belier: "A confidence built through boldness and the first spark: one grows by daring, by charging ahead, even at the risk of mistakes. Luck seems to favor those who take the lead.",
    taureau: "A confidence built through the concrete and through patience: one grows by consolidating what already exists rather than scattering effort. A sense of sensory abundance.",
    gemeaux: "A confidence built through curiosity and the gathering of varied knowledge: one grows by multiplying exchanges, readings, points of view.",
    cancer: "A confidence built through emotional and family bonds: one grows by caring for others, by feeling part of a protective circle, by giving without counting.",
    lion: "A generous, radiant confidence: one grows by putting oneself out there, by creating, by betting on one's own worth with a sometimes outsized optimism.",
    vierge: "A confidence built through competence and service rendered: one grows by perfecting one's skills, with a demand for rigor that can slow Jupiter's natural momentum.",
    balance: "A confidence built through relationship and fairness: one grows by partnering, by seeking balance and consensus rather than moving forward alone.",
    scorpion: "A confidence built through intensity and transformation: one grows by going through deep ordeals rather than staying on the surface of things.",
    sagittaire: "Jupiter is in its element here: optimism, a thirst for meaning and wide horizons, an almost natural faith in the future and in one's own abilities.",
    capricorne: "A confidence built over time and through discipline: one grows slowly but solidly, earning authority rather than being handed it.",
    verseau: "A confidence built through deliberate difference and belonging to a collective: one grows by opening up to new ideas and causes bigger than oneself.",
    poissons: "A confidence built through letting go and intuition: one grows by trusting a movement bigger than oneself, sometimes at the cost of a grip on reality.",
  },
  saturn: {
    belier: "A discipline learned through action: Saturn slows Aries' natural impulsiveness, which can feel frustrating before becoming a strength of patience.",
    taureau: "Saturn is particularly at home here: a natural sense for slow building, solidity, worth that is earned rather than given.",
    gemeaux: "A discipline learned through intellectual rigor: Saturn channels Gemini's natural scattering into more structured knowledge, sometimes at the cost of spontaneity.",
    cancer: "A discipline learned in relation to family and emotional security: often an early sense of responsibility, or an emotional reserve to move past.",
    lion: "A discipline learned in relation to recognition: self-confidence must be built step by step here, often after doubting one's own worth.",
    vierge: "A discipline learned in relation to detail and demand: Virgo's natural perfectionism can turn into harshness toward oneself here, to be softened over time.",
    balance: "A discipline learned within relationship: measured commitment, a sharp sense of fairness, but also an initial fear of commitment to move past in order to build something solid together.",
    scorpion: "A discipline learned in relation to control and transformation: a need to master inner intensity rather than flee or endure it.",
    sagittaire: "A discipline learned in relation to beliefs: Saturn structures Sagittarius' enthusiasm, forcing it to concretely verify what it believes in.",
    capricorne: "Saturn is in its element here: an innate sense of responsibility, structure and patient ambition — often an early maturity that improves with age.",
    verseau: "A discipline learned in relation to the group and to difference: giving structure to one's uniqueness so it serves a collective project rather than staying marginal.",
    poissons: "A discipline learned in relation to vagueness and letting go: giving concrete form to intuition and sensitivity, without smothering them.",
  },
  asc: {
    belier: "A brisk, direct bearing, a frank approach that gets straight to the point. The first impression given is one of energy ready for a challenge.",
    taureau: "A steady, reassuring presence, grounded in the body and the concrete. The pace is slow, but the solidity of the bearing inspires confidence.",
    gemeaux: "A quick, curious, talkative approach: attention is caught fast through wit and easy contact, with a bearing that's often youthful or restless.",
    cancer: "A soft, sensitive presence, sometimes reserved at first — taking time to assess whether the environment is safe before opening up further.",
    lion: "A bearing that doesn't go unnoticed: presence, warmth, a natural sense for self-presentation.",
    vierge: "A discreet, well put-together presence, often perceived as serious and competent from the first contact.",
    balance: "A charming, courteous approach, aesthetically polished, with a real concern for making a good impression and creating a pleasant relationship.",
    scorpion: "A magnetic, intense presence that intrigues and sometimes impresses — one senses right away a depth that doesn't reveal itself easily.",
    sagittaire: "A cheerful, frank bearing, sometimes brimming with enthusiasm — humor and optimism are often the first calling card.",
    capricorne: "A sober, reserved presence that immediately inspires seriousness and reliability — sometimes perceived as distant before being better known.",
    verseau: "An original, slightly offbeat approach that displays its difference without hesitation from the very first meeting.",
    poissons: "A soft, dreamy, sometimes elusive presence — the gaze often seems to drift elsewhere.",
  },
};
