import type { PointKey } from "../types";

/**
 * Textes dédiés par planète × 12 maisons, sur le même principe que
 * planet-in-sign.ts : structure en trois temps (ce que la maison prend
 * comme couleur avec cette planète, où ça coince, ce qu'il y a à
 * apprendre). Couverture volontairement partielle pour l'instant — les
 * combinaisons non couvertes retombent sur le gabarit générique de
 * describePlanetInHouse dans compose.ts.
 */
export const PLANET_IN_HOUSE: Partial<Record<PointKey, Record<number, string>>> = {
  sun: {
    1: "Le Soleil en maison I place l'identité en pleine lumière dès le premier regard : la présence est immédiatement lisible, l'énergie vitale se voit dans le corps, la voix, la façon d'entrer quelque part — on sait vite à qui on a affaire. Ce qui coûte le plus se joue dans le besoin d'être vu : cette identité si frontale peut glisser vers un centrage sur soi permanent, une difficulté à céder la scène, ou une confiance qui masque en réalité une dépendance au regard des autres pour se sentir exister. Le terrain de maturation est d'apprendre que la vitalité n'a pas besoin d'un public pour être réelle.",
    2: "Le Soleil en maison II ancre l'identité dans le tangible : ce qu'on possède, ce qu'on gagne, ce qu'on construit de ses mains devient une extension directe de qui l'on est, avec souvent un vrai talent pour faire fructifier des ressources. Le point sensible se loge dans la confusion des valeurs : cette identité si liée au matériel peut faire dépendre l'estime de soi du solde du compte en banque, ou pousser à prouver sa valeur par ce qu'on accumule plutôt que par ce qu'on est. Ce qu'il y a à intégrer est que la valeur personnelle précède ce qu'elle produit, elle ne s'y résume pas.",
    3: "Le Soleil en maison III exprime l'identité par la parole, la curiosité et le lien immédiat — fratrie, voisinage, échanges du quotidien : on se sent le plus soi-même en train d'apprendre, de discuter, de relier des idées entre elles. La difficulté se niche dans la dispersion : cette identité si mobile peut s'éparpiller sur trop de sujets à la fois, chercher la validation dans chaque échange plutôt que dans une pensée réellement approfondie. Grandir ici consiste à apprendre que certaines idées méritent d'être creusées jusqu'au bout plutôt que simplement évoquées.",
    4: "Le Soleil en maison IV enracine l'identité dans le foyer et les origines : on se sent pleinement soi-même dans un cadre familier, avec un besoin réel de sécurité affective pour oser se montrer ailleurs. Le revers se joue dans la fusion : cette identité si liée aux racines peut se confondre avec un rôle familial hérité — porter l'histoire des siens au point de ne plus savoir ce qui, dans cette identité, appartient vraiment en propre. Le terrain de maturation est d'apprendre que le foyer est une base, pas la totalité de qui l'on est.",
    5: "Le Soleil en maison V s'exprime pleinement dans la créativité, le jeu, l'amour et tout ce qui donne envie d'être admiré : on se sent le plus vivant en créant, en aimant sans retenue, en étant vu et applaudi pour ce qu'on fait. Ce qui coûte le plus se joue dans la dépendance à l'admiration : cette identité si tournée vers la scène peut avoir besoin d'applaudissements constants pour se sentir réelle, jusqu'à dramatiser ce qui ne l'exigeait pas. Ce qu'il y a à travailler est de continuer à créer même sans public, pour la joie du geste lui-même.",
    6: "Le Soleil en maison VI construit l'identité par l'utilité, le travail bien fait et le soin apporté au quotidien : on se sent pleinement soi-même en étant compétent, utile, capable de tenir une routine avec rigueur. Le point sensible se loge dans la fusion entre valeur et service : cette identité si centrée sur l'utilité peut s'effondrer dès qu'on ne se sent plus indispensable, pousser vers un perfectionnisme épuisant ou une identité entièrement suspendue au travail accompli. Grandir ici, c'est apprendre que la valeur personnelle ne se mérite pas uniquement par ce qu'on produit.",
    7: "Le Soleil en maison VII se révèle pleinement dans le miroir de l'autre : c'est souvent dans la relation, l'engagement ou le face-à-face qu'on se sent le plus complètement soi-même, comme si l'identité avait besoin d'un vis-à-vis pour se préciser. Le revers se joue dans la dépendance : cette identité si liée au partenariat peut se dissoudre hors de la relation, chercher chez l'autre ce qui devrait se construire en soi, ou définir sa valeur uniquement par le regard d'un partenaire. Le terrain de maturation est de bâtir une identité qui tient debout seule, avant même de se refléter dans l'autre.",
    8: "Le Soleil en maison VIII se forge dans l'intensité : crises, transformations, intimité profonde et tout ce qui touche à ce qui reste habituellement caché deviennent le terrain où l'identité se sent la plus vraie. Ce qui coûte le plus se joue dans le besoin d'intensité : cette identité si liée aux extrêmes peut se sentir vide dans le calme, rechercher la crise pour se sentir vivante, ou avoir du mal à se montrer vulnérable malgré une profondeur réelle. Ce qu'il y a à intégrer est qu'exister pleinement ne demande pas toujours une transformation ou une épreuve pour se justifier.",
    9: "Le Soleil en maison IX s'exprime à travers la quête de sens, les croyances, les études supérieures et tout horizon qui dépasse le quotidien : on se sent le plus soi-même en explorant, en enseignant, en élargissant sa vision du monde. Le point sensible se loge dans la certitude : cette identité si attachée à sa propre vérité peut glisser vers le dogmatisme, ou lier l'estime de soi à l'idée d'avoir raison plutôt qu'à l'ouverture réelle. Grandir ici, c'est apprendre que rester soi-même n'empêche pas d'accueillir une vision différente de la sienne.",
    10: "Le Soleil en maison X trouve sa pleine expression dans le rôle public, la carrière et la reconnaissance : on se sent le plus soi-même en étant vu et valorisé pour ce qu'on accomplit, avec souvent une vraie vocation à occuper une position visible. Le revers se joue dans la dépendance au statut : cette identité si tournée vers la réussite publique peut s'effondrer sans reconnaissance extérieure, pousser à un épuisement au nom de l'image, ou négliger tout ce qui, en soi, ne se montre pas. Ce qu'il y a à travailler est que la valeur personnelle ne dépend pas uniquement du titre qu'on porte.",
    11: "Le Soleil en maison XI s'exprime pleinement dans le collectif : groupes, amitiés, causes partagées et vision d'avenir deviennent le lieu où l'identité se sent la plus vivante, portée par un sentiment réel d'appartenance. Ce qui coûte le plus se joue dans la dilution : cette identité si tournée vers le groupe peut se fondre dans une cause ou une bande d'amis au point de perdre ce qui la rend singulière. Le terrain de maturation est d'apprendre à rester pleinement soi tout en appartenant vraiment à un collectif.",
    12: "Le Soleil en maison XII se vit en retrait : l'identité se sent le plus vraie dans l'invisible, le spirituel, le service discret ou l'introspection, loin des projecteurs que d'autres placements recherchent naturellement. Le point sensible se loge dans l'effacement : cette identité si peu portée vers la visibilité peut avoir du mal à revendiquer sa place, se sentir transparente, ou se sacrifier au point de ne plus savoir ce qu'elle veut vraiment pour elle-même. Ce qu'il y a à intégrer est que revendiquer une identité ne demande pas d'être constamment vue — mais demande d'exister, au moins, pour soi.",
  },
  moon: {
    1: "La Lune en maison I porte les émotions à la surface : l'humeur se lit immédiatement sur le visage ou dans l'attitude, la sensibilité colore la première impression avant même qu'un mot soit prononcé. Ce qui coûte le plus se joue dans la lisibilité : cette identité si perméable au ressenti peut faire dépendre l'image de soi des variations d'humeur du moment, au point que les autres croient connaître l'état intérieur avant qu'il ait été partagé. Le terrain de maturation est d'apprendre que le ressenti peut informer la présence sans la dicter entièrement.",
    2: "La Lune en maison II lie la sécurité émotionnelle au tangible : avoir des réserves, un cadre matériel stable, apaise profondément, parfois jusqu'à chercher du réconfort dans la nourriture, les achats ou l'accumulation. Le revers se joue dans la disproportion : cette sécurité si liée au matériel peut générer une anxiété financière hors de proportion avec la réalité, ou faire fluctuer l'estime de soi au rythme du compte en banque. Ce qu'il y a à intégrer est que la sécurité la plus solide se construit d'abord à l'intérieur, avant de se loger dans ce qu'on possède.",
    3: "La Lune en maison III a besoin de parler pour se sentir apaisée : les échanges avec la fratrie, le voisinage, les conversations du quotidien nourrissent directement l'équilibre émotionnel. Ce qui coûte le plus se joue dans l'instabilité du dialogue : cette sensibilité si liée à la parole peut basculer d'humeur au fil d'une simple conversation, ou chercher une réassurance constante à travers les mots plutôt qu'à travers un ressenti stabilisé de l'intérieur. Grandir ici, c'est apprendre que tout ce qui se ressent n'a pas besoin d'être dit à voix haute pour être vrai.",
    4: "La Lune est chez elle en maison IV : le besoin de racines, de foyer et de sécurité affective y est le plus fondamental, avec souvent une mémoire sensorielle intense de l'enfance qui continue de colorer le présent. Le point sensible se loge dans l'attachement : cette sécurité si liée au passé familial peut rendre difficile de s'en détacher émotionnellement, ou faire dépendre l'humeur entière des changements dans le cadre domestique. Ce qu'il y a à travailler est de construire un foyer intérieur, pas seulement un lieu, pour que la sécurité ne dépende plus uniquement des murs.",
    5: "La Lune en maison V trouve son apaisement dans la création, le jeu et l'amour vécu sans retenue : le besoin d'être touché émotionnellement par ce qu'on fait ou par qui on aime est réel et profond. Ce qui coûte le plus se joue dans la dépendance affective : ce besoin d'être adoré peut chercher une validation romantique ou créative constante pour se sentir bien, jusqu'à dramatiser une relation ou un projet pour continuer à ressentir cette intensité. Le terrain de maturation est d'apprendre à s'apaiser soi-même, sans attendre que l'admiration vienne de l'extérieur.",
    6: "La Lune en maison VI lie le bien-être émotionnel à la routine et à l'utilité : un quotidien bien réglé, un corps pris en charge, un sentiment d'être utile apaisent profondément — et à l'inverse, l'anxiété s'y loge facilement dans le corps. Le revers se joue dans l'hypervigilance : cette sensibilité si attachée aux détails du quotidien peut basculer vers une inquiétude excessive au moindre grain de sable dans la routine, ou faire dépendre l'équilibre intérieur entier du stress professionnel. Ce qu'il y a à intégrer est de prendre soin sans perdre son propre équilibre en chemin.",
    7: "La Lune en maison VII se régule au contact de l'autre : l'humeur du partenaire ou de la relation affecte profondément l'équilibre intérieur, avec une vraie capacité à ressentir ce que l'autre traverse, presque par fusion. Ce qui coûte le plus se joue dans la porosité : cette sensibilité si liée au lien peut faire perdre son propre centre émotionnel dans une relation, absorber les humeurs de l'autre comme si elles étaient les siennes. Le terrain de maturation est d'apprendre la proximité sans perdre son ancrage émotionnel propre.",
    8: "La Lune en maison VIII ressent tout avec une profondeur rare : l'intimité, la crise, la transformation attirent naturellement, avec une intuition souvent aiguë pour ce qui reste caché chez les autres. Le point sensible se loge dans l'intensité difficile à partager : ce ressenti si profond peut se transformer en méfiance, en jalousie ou en humeurs extrêmes vécues en privé, avec une vraie difficulté à laisser voir cette vulnérabilité. Grandir ici, c'est apprendre que la profondeur n'a pas besoin d'être dramatique pour être réelle.",
    9: "La Lune en maison IX se rassure dans le sens, la croyance et l'ailleurs : voyager, apprendre, croire en quelque chose de plus grand que le quotidien apaise véritablement, comme un besoin réel d'horizon pour se sentir bien. Ce qui coûte le plus se joue dans la fuite : ce besoin de sens peut servir à éviter un ressenti trop inconfortable en le noyant dans l'abstraction, le voyage ou la philosophie plutôt que de le traverser directement. Ce qu'il y a à travailler est que le sens aide à digérer une émotion, il ne remplace pas le fait de la ressentir.",
    10: "La Lune en maison X expose la vie émotionnelle sur la scène publique : l'humeur se lit parfois jusque dans la vie professionnelle, avec un besoin réel d'être reconnu et « porté » par sa réussite ou son rôle social. Le revers se joue dans le sacrifice du privé : ce besoin de reconnaissance peut faire dépendre l'équilibre intérieur entier de l'image professionnelle, au point de négliger des besoins émotionnels que personne ne voit. Le terrain de maturation est d'apprendre que les besoins affectifs méritent d'être pris en compte même loin des regards.",
    11: "La Lune en maison XI se sent chez elle dans le collectif : amitiés, groupes et causes partagées nourrissent profondément l'équilibre émotionnel, avec un vrai besoin d'appartenance pour se sentir bien. Ce qui coûte le plus se joue dans la loyauté au groupe : cette sensibilité si liée à l'appartenance peut rendre difficile d'exprimer un désaccord réel de peur de perdre sa place dans le cercle. Ce qu'il y a à intégrer est qu'une appartenance vraiment sûre supporte le désaccord sans se briser.",
    12: "La Lune en maison XII vit une vie émotionnelle largement invisible : une sensibilité intuitive, presque psychique, souvent tournée vers le retrait, le rêve ou le sacrifice discret plutôt que vers l'expression directe. Le point sensible se loge dans l'évitement : ce ressenti si privé peut se manifester indirectement — par le corps, les rêves, l'envie de fuir — plutôt que d'être nommé clairement. Le terrain de maturation est d'apprendre à mettre des mots sur ce qui se ressent, plutôt que de seulement le ressentir en silence.",
  },
  jupiter: {
    1: "Jupiter en maison I déborde sur l'image donnée : la présence occupe naturellement de la place, avec une confiance et un optimisme qui se lisent souvent dans la carrure, la voix ou la façon d'entrer dans une pièce — on est vu comme quelqu'un « en plus grand » avant même d'avoir dit quoi que ce soit. Ce qui coince se joue dans la mesure : cette expansion spontanée peut déborder en promesses trop généreuses, en confiance qui frôle l'excès, ou en une présence si large qu'elle laisse peu d'espace à ceux d'à côté. Le terrain de maturation consiste à apprendre que l'ampleur n'a pas besoin d'être maximale à chaque instant pour rester réelle — qu'on peut occuper sa place sans occuper toute la pièce.",
    2: "Jupiter en maison II donne un rapport large à l'argent et à ce qui rassure matériellement : la confiance qu'il y en aura toujours assez, une générosité naturelle, souvent une vraie capacité à attirer ou faire fructifier les ressources sans s'en inquiéter constamment. Le revers se loge dans l'évaluation : cet optimisme peut désaligner les dépenses des moyens réels, surestimer ce qu'on possède ou ce qu'un projet va rapporter, jusqu'à confondre confiance et imprudence. Ce qu'il y a à intégrer est qu'un chiffre précis ne trahit pas l'abondance ressentie — que la prudence budgétaire peut coexister avec la générosité plutôt que la contredire.",
    3: "Jupiter en maison III élargit tout ce qui touche à la parole et à l'entourage proche : curiosité tous azimuts, enthousiasme communicatif, une facilité à faire des liens entre des idées ou des personnes qui semblaient éloignées. La difficulté se niche dans la précision : cette générosité de pensée peut déraper en généralisations hâtives, en promesses verbales qui dépassent ce qui sera vraiment tenu, ou en une conversation si tournée vers les grandes idées qu'elle perd le détail concret. Le travail consiste à apprendre que dire moins, mais juste, porte parfois plus loin qu'un enthousiasme qui embrasse tout sans vérifier.",
    4: "Jupiter en maison IV colore le foyer et les racines d'une tonalité généreuse : une maison qui accueille largement, une famille vécue comme une ressource morale ou philosophique autant qu'affective, parfois littéralement un foyer nombreux ou en expansion. Le point sensible se loge dans l'idéalisation : ce besoin de voir grand dans les racines peut enjoliver une histoire familiale plus compliquée qu'elle n'y paraît, ou créer une attente irréaliste de ce qu'un foyer doit apporter. Le terrain de maturation est d'apprendre à aimer ses racines telles qu'elles sont réellement, pas seulement dans la version agrandie qu'on préférerait raconter.",
    5: "Jupiter en maison V amplifie le plaisir, la créativité et l'amour ludique : une capacité réelle à jouer, créer et aimer sans retenue, souvent une chance perçue dans les histoires de cœur ou les projets créatifs, et un rapport généreux aux enfants quand il y en a. Ce qui coûte le plus se joue dans la mesure du plaisir : cet appétit peut déraper en excès — dépenses, promesses amoureuses, prises de risque — pris pour de la joie de vivre plutôt que pour ce qu'ils sont. Grandir ici, c'est apprendre que le plaisir n'a pas besoin d'être démesuré pour être pleinement ressenti.",
    6: "Jupiter en maison VI cherche du sens jusque dans le quotidien : le travail et les routines fonctionnent mieux quand ils s'inscrivent dans une perspective plus large qu'une simple tâche à accomplir — une mission, un apprentissage, une progression. La tension se loge dans la discipline : cette quête de sens peut rendre les détails répétitifs pesants, pousser à trop en promettre professionnellement ou à négliger un corps qu'on croit indestructible tant qu'on se sent porté par l'élan. Ce qu'il y a à travailler est d'apprendre que la routine bien tenue est elle-même une forme de croissance, pas son contraire.",
    7: "Jupiter en maison VII fait du partenaire une figure d'ouverture : l'autre est souvent vécu comme celui ou celle qui fait grandir, élargit l'horizon, apporte une philosophie ou une culture différente — l'engagement se choisit en partie pour ce qu'il permet de devenir. Le revers se joue dans l'idéalisation : cette attente peut placer la barre trop haut, chercher un partenaire « plus grand que nature » au point de ne jamais se satisfaire de quelqu'un de réel, ou surestimer la compatibilité au moment de s'engager. Le terrain de maturation est d'apprendre à faire grandir la relation elle-même plutôt que d'attendre que l'autre s'en charge seul.",
    8: "Jupiter en maison VIII aborde les crises, les ressources partagées et l'intimité profonde avec une confiance rare pour cette maison habituellement redoutée : une capacité à traverser les épreuves en y trouvant du sens, parfois une chance réelle avec l'argent des autres (héritage, association, dette bien gérée). Ce qui coince se loge dans l'évitement : cet optimisme peut servir à contourner ce qui fait vraiment mal — une positivité de façade qui empêche de vraiment traverser le deuil, la jalousie ou la peur plutôt que de les transformer. Ce qu'il y a à intégrer est que la foi en la traversée ne dispense pas de la vivre pleinement.",
    9: "Jupiter est chez lui en maison IX : philosophie, études supérieures, voyages et croyances personnelles s'articulent naturellement, avec une soif réelle de sens et d'horizon qui dépasse le quotidien — c'est souvent ici que se construit une vision du monde structurante pour toute une vie. Le point sensible se loge dans la certitude : cette conviction peut glisser vers le dogmatisme, l'impression de détenir une vérité plus large que celle des autres, ou une générosité d'idées qui tolère mal la contradiction. Grandir ici consiste à apprendre que la vraie ouverture d'esprit accepte d'être questionnée, pas seulement de questionner.",
    10: "Jupiter en maison X porte la réputation et la carrière vers l'ampleur : une reconnaissance publique souvent facilitée, un charisme qui inspire confiance, une ambition qui vise large plutôt que de se contenter d'un poste modeste. La difficulté se niche dans la solidité : cette expansion peut aller plus vite que les fondations réelles, avec des engagements professionnels pris avant d'avoir les moyens de les tenir, ou une image publique plus grande que ce qui la soutient concrètement. Le terrain de maturation est d'apprendre à construire une réussite qui tient dans la durée, pas seulement dans l'élan du moment.",
    11: "Jupiter en maison XI élargit le réseau social et les idéaux collectifs : un cercle d'amis souvent large et varié, un vrai enthousiasme pour les causes et les projets de groupe, la conviction que l'avenir se construit collectivement. Ce qui coûte le plus se joue dans la profondeur : cette générosité relationnelle peut rester en surface, multiplier les connaissances sans vraiment approfondir les liens, ou idéaliser un groupe ou une cause au point d'en ignorer les failles réelles. Ce qu'il y a à travailler est de choisir, parmi toutes les directions possibles, celles qui méritent un engagement réellement suivi.",
    12: "Jupiter en maison XII loge la confiance et le sens dans l'invisible : une foi intérieure, spirituelle ou intuitive, qui soutient même quand rien de concret ne la justifie, parfois une chance discrète qui agit en coulisses plutôt qu'au grand jour. Le revers se joue dans l'évitement : cet optimisme peut servir à fuir ce qui est réellement caché ou douloureux — une spiritualité utilisée pour survoler plutôt que pour affronter ce que cette maison demande de regarder en face. Le terrain de maturation est d'apprendre que la foi la plus solide est celle qui a traversé l'ombre, pas celle qui l'a évitée.",
  },
};
