import type { PointKey } from "../types";

/**
 * Textes dédiés par planète × 12 maisons, sur le même principe que
 * planet-in-sign.ts : structure en trois temps (ce que la maison prend
 * comme couleur avec cette planète, où ça coince, ce qu'il y a à
 * apprendre). Couverture volontairement partielle pour l'instant — les
 * combinaisons non couvertes retombent sur le gabarit générique de
 * describePlanetInHouse dans compose.ts.
 */
export const PLANET_IN_HOUSE: Partial<Record<PointKey, Record<number, string>>> = {
  jupiter: {
    1: "Jupiter en maison I déborde sur l'image donnée : la présence occupe naturellement de la place, avec une confiance et un optimisme qui se lisent souvent dans la carrure, la voix ou la façon d'entrer dans une pièce — on est vu comme quelqu'un « en plus grand » avant même d'avoir dit quoi que ce soit. Ce qui coince se joue dans la mesure : cette expansion spontanée peut déborder en promesses trop généreuses, en confiance qui frôle l'excès, ou en une présence si large qu'elle laisse peu d'espace à ceux d'à côté. Le terrain de maturation consiste à apprendre que l'ampleur n'a pas besoin d'être maximale à chaque instant pour rester réelle — qu'on peut occuper sa place sans occuper toute la pièce.",
    2: "Jupiter en maison II donne un rapport large à l'argent et à ce qui rassure matériellement : la confiance qu'il y en aura toujours assez, une générosité naturelle, souvent une vraie capacité à attirer ou faire fructifier les ressources sans s'en inquiéter constamment. Le revers se loge dans l'évaluation : cet optimisme peut désaligner les dépenses des moyens réels, surestimer ce qu'on possède ou ce qu'un projet va rapporter, jusqu'à confondre confiance et imprudence. Ce qu'il y a à intégrer est qu'un chiffre précis ne trahit pas l'abondance ressentie — que la prudence budgétaire peut coexister avec la générosité plutôt que la contredire.",
    3: "Jupiter en maison III élargit tout ce qui touche à la parole et à l'entourage proche : curiosité tous azimuts, enthousiasme communicatif, une facilité à faire des liens entre des idées ou des personnes qui semblaient éloignées. La difficulté se niche dans la précision : cette générosité de pensée peut déraper en généralisations hâtives, en promesses verbales qui dépassent ce qui sera vraiment tenu, ou en une conversation si tournée vers les grandes idées qu'elle perd le détail concret. Le travail consiste à apprendre que dire moins, mais juste, porte parfois plus loin qu'un enthousiasme qui embrasse tout sans vérifier.",
    4: "Jupiter en maison IV colore le foyer et les racines d'une tonalité généreuse : une maison qui accueille largement, une famille vécue comme une ressource morale ou philosophique autant qu'affective, parfois littéralement un foyer nombreux ou en expansion. Le point sensible se loge dans l'idéalisation : ce besoin de voir grand dans les racines peut enjoliver une histoire familiale plus compliquée qu'elle n'y paraît, ou créer une attente irréaliste de ce qu'un foyer doit apporter. Le terrain de maturation est d'apprendre à aimer ses racines telles qu'elles sont réellement, pas seulement dans la version agrandie qu'on préférerait raconter.",
    5: "Jupiter en maison V amplifie le plaisir, la créativité et l'amour ludique : une capacité réelle à jouer, créer et aimer sans retenue, souvent une chance perçue dans les histoires de cœur ou les projets créatifs, et un rapport généreux aux enfants quand il y en a. Ce qui coûte le plus se joue dans la mesure du plaisir : cet appétit peut déraper en excès — dépenses, promesses amoureuses, prises de risque — pris pour de la joie de vivre plutôt que pour ce qu'ils sont. Grandir ici, c'est apprendre que le plaisir n'a pas besoin d'être démesuré pour être pleinement ressenti.",
    6: "Jupiter en maison VI cherche du sens jusque dans le quotidien : le travail et les routines fonctionnent mieux quand ils s'inscrivent dans une perspective plus large qu'une simple tâche à accomplir — une mission, un apprentissage, une progression. La tension se loge dans la discipline : cette quête de sens peut rendre les détails répétitifs pesants, pousser à trop en promettre professionnellement ou à négliger un corps qu'on croit indestructible tant qu'on se sent porté par l'élan. Ce qu'il y a à travailler est d'apprendre que la routine bien tenue est elle-même une forme de croissance, pas son contraire.",
    7: "Jupiter en maison VII fait du partenaire une figure d'ouverture : l'autre est souvent vécu comme celui ou celle qui fait grandir, élargit l'horizon, apporte une philosophie ou une culture différente — l'engagement se choisit en partie pour ce qu'il permet de devenir. Le revers se joue dans l'idéalisation : cette attente peut placer la barre trop haut, chercher un partenaire « plus grand que nature » au point de ne jamais se satisfaire de quelqu'un de réel, ou surestimer la compatibilité au moment de s'engager. Le terrain de maturation est d'apprendre à faire grandir la relation elle-même plutôt que d'attendre que l'autre s'en charge seul.",
    8: "Jupiter en maison VIII aborde les crises, les ressources partagées et l'intimité profonde avec une confiance rare pour cette maison habituellement redoutée : une capacité à traverser les épreuves en y trouvant du sens, parfois une chance réelle avec l'argent des autres (héritage, association, dette bien gérée). Ce qui coince se loge dans l'évitement : cet optimisme peut servir à contourner ce qui fait vraiment mal — une positivité de façade qui empêche de vraiment traverser le deuil, la jalousie ou la peur plutôt que de les transformer. Ce qu'il y a à intégrer est que la foi en la traversée ne dispense pas de la vivre pleinement.",
    9: "Jupiter est chez lui en maison IX : philosophie, études supérieures, voyages et croyances personnelles s'articulent naturellement, avec une soif réelle de sens et d'horizon qui dépasse le quotidien — c'est souvent ici que se construit une vision du monde structurante pour toute une vie. Le point sensible se loge dans la certitude : cette conviction peut glisser vers le dogmatisme, l'impression de détenir une vérité plus large que celle des autres, ou une générosité d'idées qui tolère mal la contradiction. Grandir ici consiste à apprendre que la vraie ouverture d'esprit accepte d'être questionnée, pas seulement de questionner.",
    10: "Jupiter en maison X porte la réputation et la carrière vers l'ampleur : une reconnaissance publique souvent facilitée, un charisme qui inspire confiance, une ambition qui vise large plutôt que de se contenter d'un poste modeste. La difficulté se niche dans la solidité : cette expansion peut aller plus vite que les fondations réelles, avec des engagements professionnels pris avant d'avoir les moyens de les tenir, ou une image publique plus grande que ce qui la soutient concrètement. Le terrain de maturation est d'apprendre à construire une réussite qui tient dans la durée, pas seulement dans l'élan du moment.",
    11: "Jupiter en maison XI élargit le réseau social et les idéaux collectifs : un cercle d'amis souvent large et varié, un vrai enthousiasme pour les causes et les projets de groupe, la conviction que l'avenir se construit collectivement. Ce qui coûte le plus se joue dans la profondeur : cette générosité relationnelle peut rester en surface, multiplier les connaissances sans vraiment approfondir les liens, ou idéaliser un groupe ou une cause au point d'en ignorer les failles réelles. Ce qu'il y a à travailler est de choisir, parmi toutes les directions possibles, celles qui méritent un engagement réellement suivi.",
    12: "Jupiter en maison XII loge la confiance et le sens dans l'invisible : une foi intérieure, spirituelle ou intuitive, qui soutient même quand rien de concret ne la justifie, parfois une chance discrète qui agit en coulisses plutôt qu'au grand jour. Le revers se joue dans l'évitement : cet optimisme peut servir à fuir ce qui est réellement caché ou douloureux — une spiritualité utilisée pour survoler plutôt que pour affronter ce que cette maison demande de regarder en face. Le terrain de maturation est d'apprendre que la foi la plus solide est celle qui a traversé l'ombre, pas celle qui l'a évitée.",
  },
};
