import type { PointKey } from "../types";

// English counterpart to planet-in-house.ts — see that file for the
// rationale and structure (partial coverage, generic template covers the
// rest via describePlanetInHouse in compose.ts).
export const PLANET_IN_HOUSE_EN: Partial<Record<PointKey, Record<number, string>>> = {
  jupiter: {
    1: "Jupiter in the 1st house spills into the image you give off: your presence naturally takes up room, with a confidence and optimism that often shows in build, voice, or the way you walk into a room — people register you as somehow \"larger\" before you've said a word. Where it bites is proportion: this spontaneous expansiveness can overshoot into over-generous promises, confidence that tips into excess, or a presence so wide it leaves little room for whoever's standing next to you. The growth here is learning that scale doesn't need to be maximal at every moment to still be real — you can take your place without taking the whole room.",
    2: "Jupiter in the 2nd house gives a broad relationship to money and material security: the confidence that there will always be enough, natural generosity, and often a real knack for attracting or growing resources without constantly worrying about them. The downside sits in the math: that optimism can misalign spending with actual means, overestimate what you own or what a venture will return, until confidence quietly becomes recklessness. What's worth integrating is that a precise number doesn't betray the abundance you feel — that budgeting carefully can sit alongside generosity instead of contradicting it.",
    3: "Jupiter in the 3rd house widens everything around speech and your immediate circle: wide-ranging curiosity, contagious enthusiasm, an ease at connecting ideas or people that seemed unrelated. The friction lives in precision: that generosity of mind can slide into hasty generalizations, verbal promises that outrun what actually gets delivered, or conversation so focused on the big picture it loses the concrete detail. The work is learning that saying less, but exactly, sometimes carries further than an enthusiasm that reaches for everything without checking.",
    4: "Jupiter in the 4th house colors home and roots with a generous tone: a household that welcomes widely, a family experienced as a moral or philosophical resource as much as an emotional one, sometimes literally a large or expanding household. The sensitive point sits in idealizing: this need to see roots as bigger than life can dress up a family history that's actually messier than it looks, or build unrealistic expectations of what a home is supposed to provide. The growth here is learning to love your roots as they actually are, not only in the enlarged version you'd rather tell.",
    5: "Jupiter in the 5th house amplifies pleasure, creativity, and playful love: a real capacity to play, create, and love without holding back, often a felt sense of luck in romance or creative projects, and a generous relationship to children where there are any. What costs the most sits in gauging pleasure: this appetite can slide into excess — spending, romantic promises, risk-taking — mistaken for joie de vivre rather than seen for what it is. Growing here means learning that pleasure doesn't need to be oversized to be fully felt.",
    6: "Jupiter in the 6th house looks for meaning even in the everyday: work and routines function better when they fit inside something larger than a mere task — a mission, a form of learning, a sense of progress. The tension sits in discipline: this search for meaning can make repetitive detail feel heavy, push you to over-promise professionally, or neglect a body you assume is indestructible as long as you feel carried by momentum. The work is learning that a routine kept well is itself a form of growth, not its opposite.",
    7: "Jupiter in the 7th house turns the partner into a figure of opening: the other is often experienced as the one who helps you grow, widens your horizon, brings a different philosophy or culture — commitment gets chosen partly for what it lets you become. The downside sits in idealizing: this expectation can set the bar too high, chase a partner who feels \"larger than life\" to the point of never settling for someone real, or overestimate compatibility at the moment of committing. The growth here is learning to grow the relationship itself rather than waiting for the other person to carry that alone.",
    8: "Jupiter in the 8th house approaches crisis, shared resources, and deep intimacy with a confidence rare for this usually-dreaded house: an ability to move through hardship and find meaning in it, sometimes real luck with other people's money (inheritance, partnership, well-handled debt). Where it bites is avoidance: that optimism can be used to sidestep what actually hurts — a surface-level positivity that keeps you from truly moving through grief, jealousy, or fear rather than transforming them. What's worth integrating is that faith in getting through something doesn't excuse skipping actually living through it.",
    9: "Jupiter is at home in the 9th house: philosophy, higher learning, travel, and personal belief line up naturally, with a real hunger for meaning and horizon that reaches beyond the everyday — this is often where a whole life's worldview gets built. The sensitive point sits in certainty: that conviction can slide toward dogmatism, the sense of holding a truth wider than anyone else's, or a generosity of ideas that tolerates contradiction poorly. Growing here means learning that real open-mindedness accepts being questioned, not only doing the questioning.",
    10: "Jupiter in the 10th house carries reputation and career toward scale: public recognition often comes easily, a charisma that inspires trust, ambition that aims wide rather than settling for a modest role. The difficulty lives in solidity: this expansion can outrun the actual foundations, with professional commitments made before you have the means to keep them, or a public image bigger than what concretely supports it. The growth here is learning to build success that holds over time, not only in the rush of the moment.",
    11: "Jupiter in the 11th house widens your social network and collective ideals: a circle of friends that's often large and varied, real enthusiasm for causes and group projects, a conviction that the future gets built together. What costs the most sits in depth: this relational generosity can stay on the surface, multiplying acquaintances without really deepening bonds, or idealizing a group or cause to the point of ignoring its real flaws. The work is choosing, among all the possible directions, the ones that deserve genuinely sustained commitment.",
    12: "Jupiter in the 12th house places faith and meaning in the invisible: an inner, spiritual or intuitive trust that holds you up even when nothing concrete justifies it, sometimes a quiet luck that works behind the scenes rather than out in the open. The downside sits in avoidance: that optimism can be used to flee what's actually hidden or painful — a spirituality used to skim over rather than face what this house asks you to look at directly. The growth here is learning that the sturdiest faith is the one that has moved through the shadow, not the one that avoided it.",
  },
};
