// Repères des pays pour se situer sur la carte d'astrocartographie —
// coordonnées approximatives (capitale ou centroïde), suffisantes pour un
// repère visuel, pas pour une précision cartographique. `dx`/`dy` (en
// pixels, optionnels) permettent d'espacer à la main les libellés dans les
// zones denses (Europe de l'Ouest, Asie de l'Est) pour qu'ils restent
// lisibles malgré la petite taille de la carte.
//
// La liste couvre désormais tous les pays de la géométrie `world-atlas`
// (175, hors Antarctique et les terres australes françaises inhabitées) :
// chaque pays y est cliquable sur la carte et sélectionnable dans le
// classement/menu déroulant. Seul un sous-ensemble porte `labeled: true` —
// afficher un texte pour 175 pays à la fois rendrait la carte illisible,
// alors que le survol/la sélection donne déjà le nom de n'importe lequel
// via son <title> natif (voir ProjectedLine.ts et AstrocartographyMap.tsx).
export interface MajorCountry {
  /** Identifiant stable, indépendant de la langue (utilisé pour joindre FR/EN et pour le paramètre d'URL du sélecteur de pays). */
  id: string;
  name: string;
  lat: number;
  lon: number;
  dx?: number;
  dy?: number;
  /** Affiche un libellé texte permanent sur la carte (réservé à un sous-ensemble de grands pays repères, pour ne pas surcharger visuellement la carte). */
  labeled?: boolean;
  /** Nom exact du pays dans les données topojson `world-atlas` (toujours en anglais) — sert à retrouver la géométrie réelle du pays pour le calcul des lignes d'astrocartographie qui le traversent. */
  topoName: string;
}

export const MAJOR_COUNTRIES: MajorCountry[] = [
  { id: "us", name: "États-Unis", lat: 39, lon: -98, labeled: true, topoName: "United States of America" },
  { id: "ca", name: "Canada", lat: 56, lon: -106, labeled: true, topoName: "Canada" },
  { id: "mx", name: "Mexique", lat: 23, lon: -102, labeled: true, topoName: "Mexico" },
  { id: "br", name: "Brésil", lat: -10, lon: -52, labeled: true, topoName: "Brazil" },
  { id: "ar", name: "Argentine", lat: -35, lon: -64, labeled: true, topoName: "Argentina" },
  { id: "fr", name: "France", lat: 47, lon: 2, dy: 6, labeled: true, topoName: "France" },
  { id: "gb", name: "Royaume-Uni", lat: 54, lon: -2, dy: -12, labeled: true, topoName: "United Kingdom" },
  { id: "es", name: "Espagne", lat: 40, lon: -3.7, dx: 20, dy: 18, labeled: true, topoName: "Spain" },
  { id: "pt", name: "Portugal", lat: 39.5, lon: -8, dx: -32, dy: 16, labeled: true, topoName: "Portugal" },
  { id: "de", name: "Allemagne", lat: 51, lon: 10, dx: 18, dy: -4, labeled: true, topoName: "Germany" },
  { id: "it", name: "Italie", lat: 42.5, lon: 12.5, dx: 16, dy: 20, labeled: true, topoName: "Italy" },
  { id: "ru", name: "Russie", lat: 61, lon: 60, labeled: true, topoName: "Russia" },
  { id: "ma", name: "Maroc", lat: 31.8, lon: -7, dy: 14, labeled: true, topoName: "Morocco" },
  { id: "eg", name: "Égypte", lat: 26.8, lon: 30.8, labeled: true, topoName: "Egypt" },
  { id: "ng", name: "Nigéria", lat: 9.1, lon: 8, labeled: true, topoName: "Nigeria" },
  { id: "za", name: "Afrique du Sud", lat: -29, lon: 24, labeled: true, topoName: "South Africa" },
  { id: "sa", name: "Arabie saoudite", lat: 24, lon: 45, dy: 8, labeled: true, topoName: "Saudi Arabia" },
  { id: "tr", name: "Turquie", lat: 39, lon: 35, dy: -10, labeled: true, topoName: "Turkey" },
  { id: "in", name: "Inde", lat: 22, lon: 79, labeled: true, topoName: "India" },
  { id: "cn", name: "Chine", lat: 35, lon: 103, dx: -10, labeled: true, topoName: "China" },
  { id: "jp", name: "Japon", lat: 36.5, lon: 138, dx: 10, dy: -12, labeled: true, topoName: "Japan" },
  { id: "kr", name: "Corée du Sud", lat: 36, lon: 127.8, dx: -6, dy: 12, labeled: true, topoName: "South Korea" },
  { id: "id", name: "Indonésie", lat: -2, lon: 118, labeled: true, topoName: "Indonesia" },
  { id: "au", name: "Australie", lat: -25, lon: 134, labeled: true, topoName: "Australia" },
  // --- Reste du monde : cliquables et classables, sans libellé permanent sur la carte ---
  { id: "af", name: "Afghanistan", lat: 33.9, lon: 67.8, topoName: "Afghanistan" },
  { id: "al", name: "Albanie", lat: 41.2, lon: 20.2, topoName: "Albania" },
  { id: "dz", name: "Algérie", lat: 28.1, lon: 1.7, topoName: "Algeria" },
  { id: "ao", name: "Angola", lat: -11.2, lon: 17.9, topoName: "Angola" },
  { id: "am", name: "Arménie", lat: 40, lon: 45, topoName: "Armenia" },
  { id: "at", name: "Autriche", lat: 47.7, lon: 13.2, topoName: "Austria" },
  { id: "az", name: "Azerbaïdjan", lat: 40.1, lon: 47.6, topoName: "Azerbaijan" },
  { id: "bs", name: "Bahamas", lat: 25.4, lon: -78, topoName: "Bahamas" },
  { id: "bd", name: "Bangladesh", lat: 23.6, lon: 90.4, topoName: "Bangladesh" },
  { id: "be", name: "Belgique", lat: 50.5, lon: 4.3, topoName: "Belgium" },
  { id: "bz", name: "Belize", lat: 17.2, lon: -88.7, topoName: "Belize" },
  { id: "bj", name: "Bénin", lat: 9.2, lon: 2.3, topoName: "Benin" },
  { id: "bt", name: "Bhoutan", lat: 27.5, lon: 90.5, topoName: "Bhutan" },
  { id: "by", name: "Biélorussie", lat: 53.7, lon: 27.9, topoName: "Belarus" },
  { id: "mm", name: "Birmanie", lat: 19.1, lon: 96.7, topoName: "Myanmar" },
  { id: "bo", name: "Bolivie", lat: -16.3, lon: -63.5, topoName: "Bolivia" },
  { id: "ba", name: "Bosnie-Herzégovine", lat: 43.9, lon: 17.7, topoName: "Bosnia and Herz." },
  { id: "bw", name: "Botswana", lat: -22.2, lon: 24.7, topoName: "Botswana" },
  { id: "bn", name: "Brunei", lat: 4.7, lon: 114.8, topoName: "Brunei" },
  { id: "bg", name: "Bulgarie", lat: 42.7, lon: 25.5, topoName: "Bulgaria" },
  { id: "bf", name: "Burkina Faso", lat: 12.4, lon: -1.6, topoName: "Burkina Faso" },
  { id: "bi", name: "Burundi", lat: -3.4, lon: 29.9, topoName: "Burundi" },
  { id: "kh", name: "Cambodge", lat: 12.5, lon: 105, topoName: "Cambodia" },
  { id: "cm", name: "Cameroun", lat: 7.3, lon: 12.2, topoName: "Cameroon" },
  { id: "cl", name: "Chili", lat: -36.6, lon: -71.3, topoName: "Chile" },
  { id: "cy", name: "Chypre", lat: 34.9, lon: 33.1, topoName: "Cyprus" },
  { id: "xn", name: "Chypre du Nord", lat: 35.3, lon: 33.7, topoName: "N. Cyprus" },
  { id: "co", name: "Colombie", lat: 4.1, lon: -72.9, topoName: "Colombia" },
  { id: "cg", name: "Congo", lat: -0.7, lon: 14.8, topoName: "Congo" },
  { id: "kp", name: "Corée du Nord", lat: 40.3, lon: 127.5, topoName: "North Korea" },
  { id: "cr", name: "Costa Rica", lat: 9.7, lon: -84.2, topoName: "Costa Rica" },
  { id: "ci", name: "Côte d'Ivoire", lat: 7.4, lon: -5.6, topoName: "Côte d'Ivoire" },
  { id: "hr", name: "Croatie", lat: 44.5, lon: 16.5, topoName: "Croatia" },
  { id: "cu", name: "Cuba", lat: 21.5, lon: -79.6, topoName: "Cuba" },
  { id: "dk", name: "Danemark", lat: 56.3, lon: 10.4, topoName: "Denmark" },
  { id: "dj", name: "Djibouti", lat: 11.8, lon: 42.5, topoName: "Djibouti" },
  { id: "ae", name: "Émirats arabes unis", lat: 24.3, lon: 54, topoName: "United Arab Emirates" },
  { id: "ec", name: "Équateur", lat: -1.8, lon: -78.1, topoName: "Ecuador" },
  { id: "er", name: "Érythrée", lat: 15.2, lon: 39.7, topoName: "Eritrea" },
  { id: "ee", name: "Estonie", lat: 58.5, lon: 25.7, topoName: "Estonia" },
  { id: "sz", name: "Eswatini", lat: -26.5, lon: 31.4, topoName: "eSwatini" },
  { id: "et", name: "Éthiopie", lat: 9.2, lon: 40.4, topoName: "Ethiopia" },
  { id: "fj", name: "Fidji", lat: -17.2, lon: 178.7, topoName: "Fiji" },
  { id: "fi", name: "Finlande", lat: 65, lon: 26.1, topoName: "Finland" },
  { id: "ga", name: "Gabon", lat: -0.8, lon: 11.6, topoName: "Gabon" },
  { id: "gm", name: "Gambie", lat: 13.5, lon: -15.3, topoName: "Gambia" },
  { id: "ge", name: "Géorgie", lat: 42.3, lon: 43.3, topoName: "Georgia" },
  { id: "gh", name: "Ghana", lat: 7.9, lon: -1.1, topoName: "Ghana" },
  { id: "gr", name: "Grèce", lat: 38.4, lon: 23.4, topoName: "Greece" },
  { id: "gl", name: "Groenland", lat: 71.8, lon: -42.8, topoName: "Greenland" },
  { id: "gt", name: "Guatemala", lat: 15.8, lon: -90.2, topoName: "Guatemala" },
  { id: "gn", name: "Guinée", lat: 9.9, lon: -11.5, topoName: "Guinea" },
  { id: "gq", name: "Guinée équatoriale", lat: 1.6, lon: 10.3, topoName: "Eq. Guinea" },
  { id: "gw", name: "Guinée-Bissau", lat: 11.8, lon: -15.2, topoName: "Guinea-Bissau" },
  { id: "gy", name: "Guyana", lat: 4.8, lon: -59, topoName: "Guyana" },
  { id: "ht", name: "Haïti", lat: 19, lon: -73, topoName: "Haiti" },
  { id: "hn", name: "Honduras", lat: 14.5, lon: -86.3, topoName: "Honduras" },
  { id: "hu", name: "Hongrie", lat: 47.2, lon: 19.5, topoName: "Hungary" },
  { id: "fk", name: "Îles Malouines", lat: -51.7, lon: -59.5, topoName: "Falkland Is." },
  { id: "sb", name: "Îles Salomon", lat: -8.7, lon: 159.4, topoName: "Solomon Is." },
  { id: "iq", name: "Irak", lat: 33.2, lon: 43.7, topoName: "Iraq" },
  { id: "ir", name: "Iran", lat: 32.4, lon: 53.7, topoName: "Iran" },
  { id: "ie", name: "Irlande", lat: 53.4, lon: -8, topoName: "Ireland" },
  { id: "is", name: "Islande", lat: 65, lon: -19, topoName: "Iceland" },
  { id: "il", name: "Israël", lat: 31.4, lon: 35.1, topoName: "Israel" },
  { id: "jm", name: "Jamaïque", lat: 18.1, lon: -77.3, topoName: "Jamaica" },
  { id: "jo", name: "Jordanie", lat: 31.3, lon: 37.1, topoName: "Jordan" },
  { id: "kz", name: "Kazakhstan", lat: 48, lon: 66.9, topoName: "Kazakhstan" },
  { id: "ke", name: "Kenya", lat: 0.4, lon: 37.9, topoName: "Kenya" },
  { id: "kg", name: "Kirghizistan", lat: 41.3, lon: 74.9, topoName: "Kyrgyzstan" },
  { id: "xk", name: "Kosovo", lat: 42.6, lon: 20.9, topoName: "Kosovo" },
  { id: "kw", name: "Koweït", lat: 29.3, lon: 47.5, topoName: "Kuwait" },
  { id: "la", name: "Laos", lat: 18.2, lon: 103.8, topoName: "Laos" },
  { id: "ls", name: "Lesotho", lat: -29.6, lon: 28.2, topoName: "Lesotho" },
  { id: "lv", name: "Lettonie", lat: 56.8, lon: 24.6, topoName: "Latvia" },
  { id: "lb", name: "Liban", lat: 33.9, lon: 35.9, topoName: "Lebanon" },
  { id: "lr", name: "Liberia", lat: 6.4, lon: -9.5, topoName: "Liberia" },
  { id: "ly", name: "Libye", lat: 26.4, lon: 17.2, topoName: "Libya" },
  { id: "lt", name: "Lituanie", lat: 55.1, lon: 23.8, topoName: "Lithuania" },
  { id: "lu", name: "Luxembourg", lat: 49.8, lon: 6, topoName: "Luxembourg" },
  { id: "mk", name: "Macédoine du Nord", lat: 41.6, lon: 21.7, topoName: "Macedonia" },
  { id: "mg", name: "Madagascar", lat: -18.8, lon: 46.9, topoName: "Madagascar" },
  { id: "my", name: "Malaisie", lat: 3.9, lon: 109.6, topoName: "Malaysia" },
  { id: "mw", name: "Malawi", lat: -13, lon: 34.2, topoName: "Malawi" },
  { id: "ml", name: "Mali", lat: 17.5, lon: -3.9, topoName: "Mali" },
  { id: "mr", name: "Mauritanie", lat: 21, lon: -11, topoName: "Mauritania" },
  { id: "md", name: "Moldavie", lat: 47, lon: 28.3, topoName: "Moldova" },
  { id: "mn", name: "Mongolie", lat: 46.8, lon: 103.8, topoName: "Mongolia" },
  { id: "me", name: "Monténégro", lat: 42.7, lon: 19.4, topoName: "Montenegro" },
  { id: "mz", name: "Mozambique", lat: -18.5, lon: 35.5, topoName: "Mozambique" },
  { id: "na", name: "Namibie", lat: -23, lon: 18.4, topoName: "Namibia" },
  { id: "np", name: "Népal", lat: 28.4, lon: 84.1, topoName: "Nepal" },
  { id: "ni", name: "Nicaragua", lat: 12.9, lon: -85.4, topoName: "Nicaragua" },
  { id: "ne", name: "Niger", lat: 17.6, lon: 8.1, topoName: "Niger" },
  { id: "no", name: "Norvège", lat: 69.4, lon: 18.1, topoName: "Norway" },
  { id: "nc", name: "Nouvelle-Calédonie", lat: -21.3, lon: 165.6, topoName: "New Caledonia" },
  { id: "nz", name: "Nouvelle-Zélande", lat: -40.5, lon: 172.5, topoName: "New Zealand" },
  { id: "om", name: "Oman", lat: 21.5, lon: 55.9, topoName: "Oman" },
  { id: "ug", name: "Ouganda", lat: 1.4, lon: 32.3, topoName: "Uganda" },
  { id: "uz", name: "Ouzbékistan", lat: 41.4, lon: 64.5, topoName: "Uzbekistan" },
  { id: "pk", name: "Pakistan", lat: 30.4, lon: 69.4, topoName: "Pakistan" },
  { id: "ps", name: "Palestine", lat: 31.9, lon: 35.2, topoName: "Palestine" },
  { id: "pa", name: "Panama", lat: 8.4, lon: -80.1, topoName: "Panama" },
  { id: "pg", name: "Papouasie-Nouvelle-Guinée", lat: -6.6, lon: 148.5, topoName: "Papua New Guinea" },
  { id: "py", name: "Paraguay", lat: -23.4, lon: -58.5, topoName: "Paraguay" },
  { id: "nl", name: "Pays-Bas", lat: 52.2, lon: 5.2, topoName: "Netherlands" },
  { id: "pe", name: "Pérou", lat: -9.2, lon: -75, topoName: "Peru" },
  { id: "ph", name: "Philippines", lat: 12, lon: 121.9, topoName: "Philippines" },
  { id: "pl", name: "Pologne", lat: 51.9, lon: 19.1, topoName: "Poland" },
  { id: "pr", name: "Porto Rico", lat: 18.2, lon: -66.4, topoName: "Puerto Rico" },
  { id: "qa", name: "Qatar", lat: 25.3, lon: 51.2, topoName: "Qatar" },
  { id: "cf", name: "République centrafricaine", lat: 6.7, lon: 20.9, topoName: "Central African Rep." },
  { id: "cd", name: "République démocratique du Congo", lat: -4, lon: 21.7, topoName: "Dem. Rep. Congo" },
  { id: "do", name: "République dominicaine", lat: 18.7, lon: -70.1, topoName: "Dominican Rep." },
  { id: "ro", name: "Roumanie", lat: 46, lon: 24.9, topoName: "Romania" },
  { id: "rw", name: "Rwanda", lat: -2, lon: 29.9, topoName: "Rwanda" },
  { id: "eh", name: "Sahara occidental", lat: 24.3, lon: -12.9, topoName: "W. Sahara" },
  { id: "sv", name: "Salvador", lat: 13.8, lon: -88.9, topoName: "El Salvador" },
  { id: "sn", name: "Sénégal", lat: 14.5, lon: -14.5, topoName: "Senegal" },
  { id: "rs", name: "Serbie", lat: 44.2, lon: 20.9, topoName: "Serbia" },
  { id: "sl", name: "Sierra Leone", lat: 8.4, lon: -11.7, topoName: "Sierra Leone" },
  { id: "sk", name: "Slovaquie", lat: 48.7, lon: 19.7, topoName: "Slovakia" },
  { id: "si", name: "Slovénie", lat: 46.2, lon: 15.1, topoName: "Slovenia" },
  { id: "so", name: "Somalie", lat: 5.2, lon: 46.1, topoName: "Somalia" },
  { id: "so-land", name: "Somaliland", lat: 9.7, lon: 45.8, topoName: "Somaliland" },
  { id: "sd", name: "Soudan", lat: 15.1, lon: 30.2, topoName: "Sudan" },
  { id: "ss", name: "Soudan du Sud", lat: 7.9, lon: 29.6, topoName: "S. Sudan" },
  { id: "lk", name: "Sri Lanka", lat: 7.9, lon: 80.7, topoName: "Sri Lanka" },
  { id: "se", name: "Suède", lat: 62.2, lon: 17.5, topoName: "Sweden" },
  { id: "ch", name: "Suisse", lat: 46.8, lon: 8.2, topoName: "Switzerland" },
  { id: "sr", name: "Suriname", lat: 3.9, lon: -56, topoName: "Suriname" },
  { id: "sy", name: "Syrie", lat: 34.8, lon: 39, topoName: "Syria" },
  { id: "tj", name: "Tadjikistan", lat: 38.8, lon: 71.2, topoName: "Tajikistan" },
  { id: "tw", name: "Taïwan", lat: 23.6, lon: 121, topoName: "Taiwan" },
  { id: "tz", name: "Tanzanie", lat: -6.3, lon: 34.8, topoName: "Tanzania" },
  { id: "td", name: "Tchad", lat: 15.4, lon: 18.7, topoName: "Chad" },
  { id: "cz", name: "Tchéquie", lat: 49.8, lon: 15.5, topoName: "Czechia" },
  { id: "th", name: "Thaïlande", lat: 13.1, lon: 101.5, topoName: "Thailand" },
  { id: "tl", name: "Timor oriental", lat: -8.8, lon: 126.2, topoName: "Timor-Leste" },
  { id: "tg", name: "Togo", lat: 8.5, lon: 0.9, topoName: "Togo" },
  { id: "tt", name: "Trinité-et-Tobago", lat: 10.4, lon: -61.4, topoName: "Trinidad and Tobago" },
  { id: "tn", name: "Tunisie", lat: 33.8, lon: 9.5, topoName: "Tunisia" },
  { id: "tm", name: "Turkménistan", lat: 39, lon: 59.5, topoName: "Turkmenistan" },
  { id: "ua", name: "Ukraine", lat: 48.8, lon: 31.1, topoName: "Ukraine" },
  { id: "uy", name: "Uruguay", lat: -32.5, lon: -55.8, topoName: "Uruguay" },
  { id: "vu", name: "Vanuatu", lat: -15.6, lon: 167.2, topoName: "Vanuatu" },
  { id: "ve", name: "Venezuela", lat: 6.4, lon: -66.5, topoName: "Venezuela" },
  { id: "vn", name: "Vietnam", lat: 16, lon: 105.8, topoName: "Vietnam" },
  { id: "ye", name: "Yémen", lat: 15.8, lon: 47.9, topoName: "Yemen" },
  { id: "zm", name: "Zambie", lat: -13.1, lon: 27.7, topoName: "Zambia" },
  { id: "zw", name: "Zimbabwe", lat: -18.9, lon: 29.1, topoName: "Zimbabwe" },
];
