import type { MajorCountry } from "./majorCountries";

export const MAJOR_COUNTRIES_EN: MajorCountry[] = [
  { id: "us", name: "United States", lat: 39, lon: -98, labeled: true, topoName: "United States of America" },
  { id: "ca", name: "Canada", lat: 56, lon: -106, labeled: true, topoName: "Canada" },
  { id: "mx", name: "Mexico", lat: 23, lon: -102, labeled: true, topoName: "Mexico" },
  { id: "br", name: "Brazil", lat: -10, lon: -52, labeled: true, topoName: "Brazil" },
  { id: "ar", name: "Argentina", lat: -35, lon: -64, labeled: true, topoName: "Argentina" },
  { id: "fr", name: "France", lat: 47, lon: 2, dy: 6, labeled: true, topoName: "France" },
  { id: "gb", name: "United Kingdom", lat: 54, lon: -2, dy: -12, labeled: true, topoName: "United Kingdom" },
  { id: "es", name: "Spain", lat: 40, lon: -3.7, dx: 20, dy: 18, labeled: true, topoName: "Spain" },
  { id: "pt", name: "Portugal", lat: 39.5, lon: -8, dx: -32, dy: 16, labeled: true, topoName: "Portugal" },
  { id: "de", name: "Germany", lat: 51, lon: 10, dx: 18, dy: -4, labeled: true, topoName: "Germany" },
  { id: "it", name: "Italy", lat: 42.5, lon: 12.5, dx: 16, dy: 20, labeled: true, topoName: "Italy" },
  { id: "ru", name: "Russia", lat: 61, lon: 60, labeled: true, topoName: "Russia" },
  { id: "ma", name: "Morocco", lat: 31.8, lon: -7, dy: 14, labeled: true, topoName: "Morocco" },
  { id: "eg", name: "Egypt", lat: 26.8, lon: 30.8, labeled: true, topoName: "Egypt" },
  { id: "ng", name: "Nigeria", lat: 9.1, lon: 8, labeled: true, topoName: "Nigeria" },
  { id: "za", name: "South Africa", lat: -29, lon: 24, labeled: true, topoName: "South Africa" },
  { id: "sa", name: "Saudi Arabia", lat: 24, lon: 45, dy: 8, labeled: true, topoName: "Saudi Arabia" },
  { id: "tr", name: "Turkey", lat: 39, lon: 35, dy: -10, labeled: true, topoName: "Turkey" },
  { id: "in", name: "India", lat: 22, lon: 79, labeled: true, topoName: "India" },
  { id: "cn", name: "China", lat: 35, lon: 103, dx: -10, labeled: true, topoName: "China" },
  { id: "jp", name: "Japan", lat: 36.5, lon: 138, dx: 10, dy: -12, labeled: true, topoName: "Japan" },
  { id: "kr", name: "South Korea", lat: 36, lon: 127.8, dx: -6, dy: 12, labeled: true, topoName: "South Korea" },
  { id: "id", name: "Indonesia", lat: -2, lon: 118, labeled: true, topoName: "Indonesia" },
  { id: "au", name: "Australia", lat: -25, lon: 134, labeled: true, topoName: "Australia" },
  // --- Rest of the world: clickable and rankable, no permanent map label ---
  { id: "af", name: "Afghanistan", lat: 33.9, lon: 67.8, topoName: "Afghanistan" },
  { id: "al", name: "Albania", lat: 41.2, lon: 20.2, topoName: "Albania" },
  { id: "dz", name: "Algeria", lat: 28.1, lon: 1.7, topoName: "Algeria" },
  { id: "ao", name: "Angola", lat: -11.2, lon: 17.9, topoName: "Angola" },
  { id: "am", name: "Armenia", lat: 40, lon: 45, topoName: "Armenia" },
  { id: "at", name: "Austria", lat: 47.7, lon: 13.2, topoName: "Austria" },
  { id: "az", name: "Azerbaijan", lat: 40.1, lon: 47.6, topoName: "Azerbaijan" },
  { id: "bs", name: "Bahamas", lat: 25.4, lon: -78, topoName: "Bahamas" },
  { id: "bd", name: "Bangladesh", lat: 23.6, lon: 90.4, topoName: "Bangladesh" },
  { id: "by", name: "Belarus", lat: 53.7, lon: 27.9, topoName: "Belarus" },
  { id: "be", name: "Belgium", lat: 50.5, lon: 4.3, topoName: "Belgium" },
  { id: "bz", name: "Belize", lat: 17.2, lon: -88.7, topoName: "Belize" },
  { id: "bj", name: "Benin", lat: 9.2, lon: 2.3, topoName: "Benin" },
  { id: "bt", name: "Bhutan", lat: 27.5, lon: 90.5, topoName: "Bhutan" },
  { id: "bo", name: "Bolivia", lat: -16.3, lon: -63.5, topoName: "Bolivia" },
  { id: "ba", name: "Bosnia and Herzegovina", lat: 43.9, lon: 17.7, topoName: "Bosnia and Herz." },
  { id: "bw", name: "Botswana", lat: -22.2, lon: 24.7, topoName: "Botswana" },
  { id: "bn", name: "Brunei", lat: 4.7, lon: 114.8, topoName: "Brunei" },
  { id: "bg", name: "Bulgaria", lat: 42.7, lon: 25.5, topoName: "Bulgaria" },
  { id: "bf", name: "Burkina Faso", lat: 12.4, lon: -1.6, topoName: "Burkina Faso" },
  { id: "bi", name: "Burundi", lat: -3.4, lon: 29.9, topoName: "Burundi" },
  { id: "kh", name: "Cambodia", lat: 12.5, lon: 105, topoName: "Cambodia" },
  { id: "cm", name: "Cameroon", lat: 7.3, lon: 12.2, topoName: "Cameroon" },
  { id: "cf", name: "Central African Republic", lat: 6.7, lon: 20.9, topoName: "Central African Rep." },
  { id: "td", name: "Chad", lat: 15.4, lon: 18.7, topoName: "Chad" },
  { id: "cl", name: "Chile", lat: -36.6, lon: -71.3, topoName: "Chile" },
  { id: "co", name: "Colombia", lat: 4.1, lon: -72.9, topoName: "Colombia" },
  { id: "cg", name: "Congo", lat: -0.7, lon: 14.8, topoName: "Congo" },
  { id: "cr", name: "Costa Rica", lat: 9.7, lon: -84.2, topoName: "Costa Rica" },
  { id: "hr", name: "Croatia", lat: 44.5, lon: 16.5, topoName: "Croatia" },
  { id: "cu", name: "Cuba", lat: 21.5, lon: -79.6, topoName: "Cuba" },
  { id: "cy", name: "Cyprus", lat: 34.9, lon: 33.1, topoName: "Cyprus" },
  { id: "cz", name: "Czechia", lat: 49.8, lon: 15.5, topoName: "Czechia" },
  { id: "cd", name: "Democratic Republic of the Congo", lat: -4, lon: 21.7, topoName: "Dem. Rep. Congo" },
  { id: "dk", name: "Denmark", lat: 56.3, lon: 10.4, topoName: "Denmark" },
  { id: "dj", name: "Djibouti", lat: 11.8, lon: 42.5, topoName: "Djibouti" },
  { id: "do", name: "Dominican Republic", lat: 18.7, lon: -70.1, topoName: "Dominican Rep." },
  { id: "ec", name: "Ecuador", lat: -1.8, lon: -78.1, topoName: "Ecuador" },
  { id: "sv", name: "El Salvador", lat: 13.8, lon: -88.9, topoName: "El Salvador" },
  { id: "gq", name: "Equatorial Guinea", lat: 1.6, lon: 10.3, topoName: "Eq. Guinea" },
  { id: "er", name: "Eritrea", lat: 15.2, lon: 39.7, topoName: "Eritrea" },
  { id: "ee", name: "Estonia", lat: 58.5, lon: 25.7, topoName: "Estonia" },
  { id: "sz", name: "Eswatini", lat: -26.5, lon: 31.4, topoName: "eSwatini" },
  { id: "et", name: "Ethiopia", lat: 9.2, lon: 40.4, topoName: "Ethiopia" },
  { id: "fk", name: "Falkland Islands", lat: -51.7, lon: -59.5, topoName: "Falkland Is." },
  { id: "fj", name: "Fiji", lat: -17.2, lon: 178.7, topoName: "Fiji" },
  { id: "fi", name: "Finland", lat: 65, lon: 26.1, topoName: "Finland" },
  { id: "ga", name: "Gabon", lat: -0.8, lon: 11.6, topoName: "Gabon" },
  { id: "gm", name: "Gambia", lat: 13.5, lon: -15.3, topoName: "Gambia" },
  { id: "ge", name: "Georgia", lat: 42.3, lon: 43.3, topoName: "Georgia" },
  { id: "gh", name: "Ghana", lat: 7.9, lon: -1.1, topoName: "Ghana" },
  { id: "gr", name: "Greece", lat: 38.4, lon: 23.4, topoName: "Greece" },
  { id: "gl", name: "Greenland", lat: 71.8, lon: -42.8, topoName: "Greenland" },
  { id: "gt", name: "Guatemala", lat: 15.8, lon: -90.2, topoName: "Guatemala" },
  { id: "gn", name: "Guinea", lat: 9.9, lon: -11.5, topoName: "Guinea" },
  { id: "gw", name: "Guinea-Bissau", lat: 11.8, lon: -15.2, topoName: "Guinea-Bissau" },
  { id: "gy", name: "Guyana", lat: 4.8, lon: -59, topoName: "Guyana" },
  { id: "ht", name: "Haiti", lat: 19, lon: -73, topoName: "Haiti" },
  { id: "hn", name: "Honduras", lat: 14.5, lon: -86.3, topoName: "Honduras" },
  { id: "hu", name: "Hungary", lat: 47.2, lon: 19.5, topoName: "Hungary" },
  { id: "is", name: "Iceland", lat: 65, lon: -19, topoName: "Iceland" },
  { id: "ir", name: "Iran", lat: 32.4, lon: 53.7, topoName: "Iran" },
  { id: "iq", name: "Iraq", lat: 33.2, lon: 43.7, topoName: "Iraq" },
  { id: "ie", name: "Ireland", lat: 53.4, lon: -8, topoName: "Ireland" },
  { id: "il", name: "Israel", lat: 31.4, lon: 35.1, topoName: "Israel" },
  { id: "ci", name: "Ivory Coast", lat: 7.4, lon: -5.6, topoName: "Côte d'Ivoire" },
  { id: "jm", name: "Jamaica", lat: 18.1, lon: -77.3, topoName: "Jamaica" },
  { id: "jo", name: "Jordan", lat: 31.3, lon: 37.1, topoName: "Jordan" },
  { id: "kz", name: "Kazakhstan", lat: 48, lon: 66.9, topoName: "Kazakhstan" },
  { id: "ke", name: "Kenya", lat: 0.4, lon: 37.9, topoName: "Kenya" },
  { id: "xk", name: "Kosovo", lat: 42.6, lon: 20.9, topoName: "Kosovo" },
  { id: "kw", name: "Kuwait", lat: 29.3, lon: 47.5, topoName: "Kuwait" },
  { id: "kg", name: "Kyrgyzstan", lat: 41.3, lon: 74.9, topoName: "Kyrgyzstan" },
  { id: "la", name: "Laos", lat: 18.2, lon: 103.8, topoName: "Laos" },
  { id: "lv", name: "Latvia", lat: 56.8, lon: 24.6, topoName: "Latvia" },
  { id: "lb", name: "Lebanon", lat: 33.9, lon: 35.9, topoName: "Lebanon" },
  { id: "ls", name: "Lesotho", lat: -29.6, lon: 28.2, topoName: "Lesotho" },
  { id: "lr", name: "Liberia", lat: 6.4, lon: -9.5, topoName: "Liberia" },
  { id: "ly", name: "Libya", lat: 26.4, lon: 17.2, topoName: "Libya" },
  { id: "lt", name: "Lithuania", lat: 55.1, lon: 23.8, topoName: "Lithuania" },
  { id: "lu", name: "Luxembourg", lat: 49.8, lon: 6, topoName: "Luxembourg" },
  { id: "mg", name: "Madagascar", lat: -18.8, lon: 46.9, topoName: "Madagascar" },
  { id: "mw", name: "Malawi", lat: -13, lon: 34.2, topoName: "Malawi" },
  { id: "my", name: "Malaysia", lat: 3.9, lon: 109.6, topoName: "Malaysia" },
  { id: "ml", name: "Mali", lat: 17.5, lon: -3.9, topoName: "Mali" },
  { id: "mr", name: "Mauritania", lat: 21, lon: -11, topoName: "Mauritania" },
  { id: "md", name: "Moldova", lat: 47, lon: 28.3, topoName: "Moldova" },
  { id: "mn", name: "Mongolia", lat: 46.8, lon: 103.8, topoName: "Mongolia" },
  { id: "me", name: "Montenegro", lat: 42.7, lon: 19.4, topoName: "Montenegro" },
  { id: "mz", name: "Mozambique", lat: -18.5, lon: 35.5, topoName: "Mozambique" },
  { id: "mm", name: "Myanmar", lat: 19.1, lon: 96.7, topoName: "Myanmar" },
  { id: "na", name: "Namibia", lat: -23, lon: 18.4, topoName: "Namibia" },
  { id: "np", name: "Nepal", lat: 28.4, lon: 84.1, topoName: "Nepal" },
  { id: "nl", name: "Netherlands", lat: 52.2, lon: 5.2, topoName: "Netherlands" },
  { id: "nc", name: "New Caledonia", lat: -21.3, lon: 165.6, topoName: "New Caledonia" },
  { id: "nz", name: "New Zealand", lat: -40.5, lon: 172.5, topoName: "New Zealand" },
  { id: "ni", name: "Nicaragua", lat: 12.9, lon: -85.4, topoName: "Nicaragua" },
  { id: "ne", name: "Niger", lat: 17.6, lon: 8.1, topoName: "Niger" },
  { id: "kp", name: "North Korea", lat: 40.3, lon: 127.5, topoName: "North Korea" },
  { id: "mk", name: "North Macedonia", lat: 41.6, lon: 21.7, topoName: "Macedonia" },
  { id: "xn", name: "Northern Cyprus", lat: 35.3, lon: 33.7, topoName: "N. Cyprus" },
  { id: "no", name: "Norway", lat: 69.4, lon: 18.1, topoName: "Norway" },
  { id: "om", name: "Oman", lat: 21.5, lon: 55.9, topoName: "Oman" },
  { id: "pk", name: "Pakistan", lat: 30.4, lon: 69.4, topoName: "Pakistan" },
  { id: "ps", name: "Palestine", lat: 31.9, lon: 35.2, topoName: "Palestine" },
  { id: "pa", name: "Panama", lat: 8.4, lon: -80.1, topoName: "Panama" },
  { id: "pg", name: "Papua New Guinea", lat: -6.6, lon: 148.5, topoName: "Papua New Guinea" },
  { id: "py", name: "Paraguay", lat: -23.4, lon: -58.5, topoName: "Paraguay" },
  { id: "pe", name: "Peru", lat: -9.2, lon: -75, topoName: "Peru" },
  { id: "ph", name: "Philippines", lat: 12, lon: 121.9, topoName: "Philippines" },
  { id: "pl", name: "Poland", lat: 51.9, lon: 19.1, topoName: "Poland" },
  { id: "pr", name: "Puerto Rico", lat: 18.2, lon: -66.4, topoName: "Puerto Rico" },
  { id: "qa", name: "Qatar", lat: 25.3, lon: 51.2, topoName: "Qatar" },
  { id: "ro", name: "Romania", lat: 46, lon: 24.9, topoName: "Romania" },
  { id: "rw", name: "Rwanda", lat: -2, lon: 29.9, topoName: "Rwanda" },
  { id: "sn", name: "Senegal", lat: 14.5, lon: -14.5, topoName: "Senegal" },
  { id: "rs", name: "Serbia", lat: 44.2, lon: 20.9, topoName: "Serbia" },
  { id: "sl", name: "Sierra Leone", lat: 8.4, lon: -11.7, topoName: "Sierra Leone" },
  { id: "sk", name: "Slovakia", lat: 48.7, lon: 19.7, topoName: "Slovakia" },
  { id: "si", name: "Slovenia", lat: 46.2, lon: 15.1, topoName: "Slovenia" },
  { id: "sb", name: "Solomon Islands", lat: -8.7, lon: 159.4, topoName: "Solomon Is." },
  { id: "so", name: "Somalia", lat: 5.2, lon: 46.1, topoName: "Somalia" },
  { id: "so-land", name: "Somaliland", lat: 9.7, lon: 45.8, topoName: "Somaliland" },
  { id: "ss", name: "South Sudan", lat: 7.9, lon: 29.6, topoName: "S. Sudan" },
  { id: "lk", name: "Sri Lanka", lat: 7.9, lon: 80.7, topoName: "Sri Lanka" },
  { id: "sd", name: "Sudan", lat: 15.1, lon: 30.2, topoName: "Sudan" },
  { id: "sr", name: "Suriname", lat: 3.9, lon: -56, topoName: "Suriname" },
  { id: "se", name: "Sweden", lat: 62.2, lon: 17.5, topoName: "Sweden" },
  { id: "ch", name: "Switzerland", lat: 46.8, lon: 8.2, topoName: "Switzerland" },
  { id: "sy", name: "Syria", lat: 34.8, lon: 39, topoName: "Syria" },
  { id: "tw", name: "Taiwan", lat: 23.6, lon: 121, topoName: "Taiwan" },
  { id: "tj", name: "Tajikistan", lat: 38.8, lon: 71.2, topoName: "Tajikistan" },
  { id: "tz", name: "Tanzania", lat: -6.3, lon: 34.8, topoName: "Tanzania" },
  { id: "th", name: "Thailand", lat: 13.1, lon: 101.5, topoName: "Thailand" },
  { id: "tl", name: "Timor-Leste", lat: -8.8, lon: 126.2, topoName: "Timor-Leste" },
  { id: "tg", name: "Togo", lat: 8.5, lon: 0.9, topoName: "Togo" },
  { id: "tt", name: "Trinidad and Tobago", lat: 10.4, lon: -61.4, topoName: "Trinidad and Tobago" },
  { id: "tn", name: "Tunisia", lat: 33.8, lon: 9.5, topoName: "Tunisia" },
  { id: "tm", name: "Turkmenistan", lat: 39, lon: 59.5, topoName: "Turkmenistan" },
  { id: "ug", name: "Uganda", lat: 1.4, lon: 32.3, topoName: "Uganda" },
  { id: "ua", name: "Ukraine", lat: 48.8, lon: 31.1, topoName: "Ukraine" },
  { id: "ae", name: "United Arab Emirates", lat: 24.3, lon: 54, topoName: "United Arab Emirates" },
  { id: "uy", name: "Uruguay", lat: -32.5, lon: -55.8, topoName: "Uruguay" },
  { id: "uz", name: "Uzbekistan", lat: 41.4, lon: 64.5, topoName: "Uzbekistan" },
  { id: "vu", name: "Vanuatu", lat: -15.6, lon: 167.2, topoName: "Vanuatu" },
  { id: "ve", name: "Venezuela", lat: 6.4, lon: -66.5, topoName: "Venezuela" },
  { id: "vn", name: "Vietnam", lat: 16, lon: 105.8, topoName: "Vietnam" },
  { id: "eh", name: "Western Sahara", lat: 24.3, lon: -12.9, topoName: "W. Sahara" },
  { id: "ye", name: "Yemen", lat: 15.8, lon: 47.9, topoName: "Yemen" },
  { id: "zm", name: "Zambia", lat: -13.1, lon: 27.7, topoName: "Zambia" },
  { id: "zw", name: "Zimbabwe", lat: -18.9, lon: 29.1, topoName: "Zimbabwe" },
];
