import type { MajorCountry } from "./majorCountries";

export const MAJOR_COUNTRIES_EN: MajorCountry[] = [
  { id: "us", name: "United States", lat: 39, lon: -98, topoName: "United States of America" },
  { id: "ca", name: "Canada", lat: 56, lon: -106, topoName: "Canada" },
  { id: "mx", name: "Mexico", lat: 23, lon: -102, topoName: "Mexico" },
  { id: "br", name: "Brazil", lat: -10, lon: -52, topoName: "Brazil" },
  { id: "ar", name: "Argentina", lat: -35, lon: -64, topoName: "Argentina" },
  { id: "fr", name: "France", lat: 47, lon: 2, dy: 6, topoName: "France" },
  { id: "gb", name: "United Kingdom", lat: 54, lon: -2, dy: -12, topoName: "United Kingdom" },
  { id: "es", name: "Spain", lat: 40, lon: -3.7, dx: 20, dy: 18, topoName: "Spain" },
  { id: "pt", name: "Portugal", lat: 39.5, lon: -8, dx: -32, dy: 16, topoName: "Portugal" },
  { id: "de", name: "Germany", lat: 51, lon: 10, dx: 18, dy: -4, topoName: "Germany" },
  { id: "it", name: "Italy", lat: 42.5, lon: 12.5, dx: 16, dy: 20, topoName: "Italy" },
  { id: "ru", name: "Russia", lat: 61, lon: 60, topoName: "Russia" },
  { id: "ma", name: "Morocco", lat: 31.8, lon: -7, dy: 14, topoName: "Morocco" },
  { id: "eg", name: "Egypt", lat: 26.8, lon: 30.8, topoName: "Egypt" },
  { id: "ng", name: "Nigeria", lat: 9.1, lon: 8, topoName: "Nigeria" },
  { id: "za", name: "South Africa", lat: -29, lon: 24, topoName: "South Africa" },
  { id: "sa", name: "Saudi Arabia", lat: 24, lon: 45, dy: 8, topoName: "Saudi Arabia" },
  { id: "tr", name: "Turkey", lat: 39, lon: 35, dy: -10, topoName: "Turkey" },
  { id: "in", name: "India", lat: 22, lon: 79, topoName: "India" },
  { id: "cn", name: "China", lat: 35, lon: 103, dx: -10, topoName: "China" },
  { id: "jp", name: "Japan", lat: 36.5, lon: 138, dx: 10, dy: -12, topoName: "Japan" },
  { id: "kr", name: "South Korea", lat: 36, lon: 127.8, dx: -6, dy: 12, topoName: "South Korea" },
  { id: "id", name: "Indonesia", lat: -2, lon: 118, topoName: "Indonesia" },
  { id: "au", name: "Australia", lat: -25, lon: 134, topoName: "Australia" },
];
